name: Build

on:
  push:

jobs:
  generate-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build Resumes with Nix
        run: nix build

      - name: Upload generated PDFs to GitHub Actions Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: resumes
          path: |
            result/resume.pdf
            result/curriculo.pdf