name: Build

on:
  push:

jobs:
  generate-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Typst
        uses: typst-community/setup-typst@v3

      - name: Build English Resume
        run: typst compile --root . resumes/en/resume.typ resumes/en/resume.pdf

      - name: Build Portuguese Resume
        run: typst compile --root . resumes/pt-br/curriculo.typ resumes/pt-br/curriculo.pdf
      
      - name: Upload generated PDFs to GitHub Actions Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: resumes
          path: |
            resumes/en/resume.pdf
            resumes/pt-br/curriculo.pdf